[package]
name = "probabilistic-choice"
version = "0.1.0"
authors = ["Daniel Watson <danielwatson311@gmail.com>"]

[package.metadata.rosettacode]
url = "https://rosettacode.org/wiki/Probabilistic_choice"

[dependencies]
rand = "0.5"
