[package]
name = "public-point-to-address"
version = "0.1.1"
edition = "2018"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Bitcoin/public_point_to_address"

[dependencies]
hex = "0.3"
ring = "0.14"
ripemd160 = "^0.8.0"
