[package]
name = "chaos-game"
version = "0.1.0"
edition = "2021"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Chaos_game"

[dependencies]
image = { version = "0.24.6", default-features = false, features = ["png"] }
rand = "0.8.5"
