language: rust
rust: nightly
sudo: false

env:
  global:
    - RUST_BACKTRACE=1
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

# `sudo`-less apt install.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
        # Needed for `travis-cargo coveralls --no-sudo`
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

# Load `travis-cargo`
before_script:
    - pip install 'travis-cargo' --user
    - export PATH=$HOME/.local/bin:$PATH

script:
    - travis-cargo build
    - travis-cargo test

# Generate Docs and coverage
after_success:
    - travis-cargo coveralls --no-sudo
