environment:
  RUST_DIR: C:\Rust\
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    BITS: 64
  - TARGET: i686-pc-windows-msvc
    BITS: 32
# Disabled due to rust-lang/rust#47029
# - TARGET: i686-pc-windows-gnu
#   BITS: 32

shallow_clone: true

cache:
  - target
  - '%USERPROFILE%\.cargo'

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.msi"
  - msiexec /i rust-nightly-%TARGET%.msi /quiet /passive /qn /norestart INSTALLDIR=%RUST_DIR%
  - SET PATH=%PATH%;%RUST_DIR%\bin
  - SET PATH=%PATH%;C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --all
