[package]
name = "plasma-effect"
version = "0.1.0"
authors = ["9names"]
edition = "2021"

[dependencies]
image = { version = "0.24.2", default-features = false, features = ["png"] }

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Plasma_effect"
