[package]
name = "kronecker-product"
version = "0.1.0"
edition = "2018"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Kronecker_product"

[dependencies]
num = "0.4.0"
ndarray = "0.15.4"
