[package]
name = "constrained-random-points-on-a-circle"
version = "0.1.0"
authors = ["Daniel Watson <danielwatson311@gmail.com>"]

[package.metadata.rosettacode]
url = "https://rosettacode.org/wiki/Constrained_random_points_on_a_circle"

[dependencies]
rand = "0.5"
