[package]
name = "atomic-updates"
version = "0.1.0"
edition = "2018"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Atomic_updates"

[dependencies]
rand = "0.7.2"
array-init = "2.0.0"
