[package]
name = "k-meanspp-clustering"
version = "0.1.0"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/K-means%2B%2B_clustering"

[dependencies]
csv = "1"
gnuplot = "0.0.37"
nalgebra = "0.31.1"
rand = "0.7.2"
structopt = "0.3.26"
