[package]
name = "k-meanspp-clustering"
version = "0.1.0"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/K-means%2B%2B_clustering"

[dependencies]
csv = "1.0.0-beta.4"
getopts = "0.2"
gnuplot = "0.0.23"
nalgebra = "0.13"
rand = "0.4"
serde = "1"
