[package]
name = "s-expressions"
version = "0.1.0"
edition = "2018"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/S-Expressions"

[dependencies]
typed-arena = "1.1.0"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "benchmarks"
harness = false
