[package]
name = "animation"
version = "0.1.0"
authors = ["Stefan MÃ¼ller <co@zzeroo.com>"]

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Animation"

[dependencies.gtk]
version = "0.1.0"
optional = true
