[package]
name = "linear-congruential-generator"
version = "0.1.0"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Linear_congruential_generator"

[dependencies]
rand = "0.7.2"
rand_core = "0.5.1"
