[package]
name = "visualize-a-tree"
version = "0.1.0"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Visualize_a_tree"

[dependencies]
rand = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
term-painter = "0.2"
